video_player/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("video_player_app.urls"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

video_player_app/urls.py
from django.urls import path
from video_player_app.views import(home,video_detail,comment_video,subscribe_channel,
    like_video,UserLogin,register,user_logout,upload_video,view_channel)

app_name="video"
urlpatterns = [
    path("home/",home,name="home"),
    path("video-detail/<int:id>/",video_detail,name="video_detail"),
    path("like-video/<int:id>/",like_video,name="video_like"),
    path("login/",UserLogin.as_view(),name="login"),
    path("register/",register,name="register"),
    path('comment/<int:id>/',comment_video,name="comment"),
    path('subsribe/<str:username>/<int:pk>',subscribe_channel,name="subscribe"),
    path("logout/",user_logout,name="logout"),
    path("upload-video/",upload_video,name="upload_video"),
    path("view_channel/<str:username>/",view_channel,name="view_channel")
]

video_player_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo=models.ImageField(upload_to='userphotos',blank=True,null=True)
    description=models.TextField(blank=True,null=True)
    class Meta:
        verbose_name="User"
        verbose_name_plural="Users"
    def __str__(self):
        return self.username

    def save(self,*args,**kwargs):
        is_new_user=self.pk
        if is_new_user:
            Channel.objects.create(name=f"{self.username}'s Channel",
            description="My channel Description",
            user=self)
        super(User, self).save(*args, **kwargs)

class Video(models.Model):
    title=models.CharField(max_length=255)
    discription=models.TextField(blank=True,null=True)
    upload_date=models.DateTimeField(auto_now_add=True)
    video_file = models.FileField(upload_to='videos/')
    thumbnail=models.ImageField(upload_to='videos/')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="video")

    def __str__(self):
        return str(self.title)

    @property
    def likes_count(self):
        return self.likes.filter(is_liked=True).count()



class Channel(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField()
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="channel")
    videos = models.ManyToManyField(Video,related_name="channel")
    def __str__(self):
        return self.name
    
    @property
    def subscribe_count(self):
        return self.subsribe.filter(is_subscribed=True).count()






    
class Comment(models.Model):
    description=models.CharField(max_length=255)
    video=models.ForeignKey(Video,on_delete=models.CASCADE,related_name="comments")
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,related_name="comments")

    def __str__(self):
        return str(self.description)
     
class Like(models.Model):
    is_liked=models.BooleanField(default=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,related_name="likes")
    video=models.ForeignKey(Video,on_delete=models.CASCADE,related_name="likes")
    def _str__(self):
        return str(self.id)

class Subscribe(models.Model):
    is_subscribed=models.BooleanField(default=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,related_name="subsribe")
    channel=models.ForeignKey(Channel,on_delete=models.CASCADE,related_name="subsribe")
    
    def _str__(self):
        return str(self.id)

   

video_player_app/forms.py
from django import forms
from video_player_app.models import User,Comment,Video
from django.contrib.auth.forms import UserCreationForm



class UserRegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=["username","password1","password2"]

class UserCommentForm(forms.ModelForm):
    description=forms.CharField(max_length=255,widget=forms.Textarea)
    class Meta:
        model=Comment
        fields=["description"]

class UserUploadVideoForm(forms.ModelForm):
    title=forms.CharField(max_length=255)
    description=forms.CharField(max_length=255,widget=forms.Textarea)
    video_file = forms.FileField()
    thumbnail=forms.ImageField()
    class Meta:
        model=Video
        fields=["title","description","video_file","thumbnail"]

video_player_app/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from .models import Video,Channel,User,Like,Comment,Subscribe
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView

from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import UserRegisterForm,UserCommentForm,UserUploadVideoForm
# from django.db.models import Count
# Create your views here.
def home(request):
    videos=Video.objects.all()
    return render(request,"home.html",{"videos":videos})


def video_detail(request,id):
    videos=Video.objects.filter(id=id)

    return render(request,"video_detail.html",{"videos":videos})

@login_required
def like_video(request,id):
    video=get_object_or_404(Video,id=id)
    user=request.user
    like,created=Like.objects.get_or_create(video=video,user=user)
    if not created:
        if like.is_liked==True:
            like.is_liked=False
        else:
            like.is_liked=True
        like.save()
    total_likes=video.likes.filter(is_liked=True).count()
    return HttpResponseRedirect(reverse("video:video_detail",args=(id,)))



class UserLogin(LoginView):
    template_name="login.html"


def register(request):
    if request.method=="POST":
        form=UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("video:login")
    else:
        form=UserRegisterForm()
    return render(request,"register.html",{"form":form})



def comment_video(request,id):
    video=get_object_or_404(Video,id=id)
    if request.method=="POST":
        form=UserCommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.video=video
            comment.user=request.user
            comment.save()
            return HttpResponseRedirect(reverse("video:comment",args=(id,)))
    else:
        form=UserCommentForm()
    comments=Comment.objects.filter(video__id=id)
    context={
        "form":form,
        "comments":comments,
    }
    return render(request,"comment.html",context)
    
@login_required
def subscribe_channel(request,username,pk):
    id=Channel.objects.get(user__username=username).id
    channel=get_object_or_404(Channel,id=id)
    user=request.user
    subscribe,created=Subscribe.objects.get_or_create(channel=channel,user=user)
    if not created:
        if subscribe.is_subscribed==True:
            subscribe.is_subscribed=False
        else:
            subscribe.is_subscribed=True
        subscribe.save()
    total_subscribe=channel.subsribe.filter(is_subscribed=True).count() 
    return HttpResponseRedirect(reverse("video:video_detail",args=(pk,)))




def user_logout(request):
    logout(request)
    return redirect("video:login")


@login_required
def upload_video(request):
    print(request.POST)
    if request.method=="POST":
        form=UserUploadVideoForm(request.POST,request.FILES)
        if form.is_valid():
            video=form.save(commit=False)
            video.user=request.user
            video.save()
            return redirect("video:home")
        else:
            print("HELLO")
            print(form.errors)
    else:
        form=UserUploadVideoForm()
    return render(request,'upload_video.html',{"form":form})



def view_channel(request,username):
    videos=Video.objects.filter(user__username=username)
    subscribers=Channel.objects.get(user__username=username).subscribe_count
    context={
        "videos":videos,"username":username,
        "subscribers":subscribers
    }
    return render(request,"view_channel.html",context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEMOTUBE</title>
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bs.min.css' %}" type="text/css"/> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    {% endblock stylesheet %}
</head>
<body>
    <div class ="container">
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock navbar%}
        {% block content %}
        {% endblock content %}
    </div>
    {% block script %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bs.min.js' %}" type="text/javascript"></script>
    {% endblock script %}

    
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'video:home' %}">DEMOTUBE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'video:home'%}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'video:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'video:upload_video' %}">Upload Video</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'video:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'video:register' %}">Register</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="#">Trending</a>
          </li>

        </ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

video_player_app/templates/comment.html
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Comment" class="btn btn-primary" />
</form>
{% for comment in comments %}
    {{ comment }}
    <br>
{% endfor %}

video_player_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<style>
    .container {
        max-width: 1200px;
        margin: 0 auto;
      }
      
      .video-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        grid-gap: 20px;
      }
      
      .video {
        border: 1px solid #ddd;
        border-radius: 5px;
        overflow: hidden;
        box-shadow: 0px 0px 5px #ddd;
        transition: transform 0.2s ease-in-out;
      }
      
      .video:hover {
        transform: scale(1.02);
      }
      
      .video-thumbnail {
        display: block;
        width: 100%;
        height: auto;
      }
      
      .video-info {
        padding: 10px;
      }
      
      .video-title {
        margin: 0;
        font-size: 1.2rem;
        font-weight: bold;
      }
      
      .video-user,
      .video-date {
        margin: 0;
        font-size: 0.9rem;
        color: #666;
      }
      
      .video-description {
        margin: 10px 0 0;
        font-size: 1rem;
        line-height: 1.2;
      }
      
</style>
  <main>
    <div class="container">
      <h2 class="section-title">Recent Videos</h2>
      <div class="video-grid">
        {% for video in videos %}
          <div class="video">
            <a href="{% url 'video:video_detail' video.pk %}">
              {% if video.thumbnail %}
              <img class="video-thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
              {% endif %}
              <div class="video-info">
                <h3 class="video-title">{{ video.title }}</h3>
                <p class="video-user">{{ video.user }}</p>
                <p class="video-date">{{ video.upload_date|date }}</p>
                <p class="video-description">{{ video.description }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </main>
{% endblock %}

video_player_app/templates/login.html
{% extends 'base.html'%}
{% block content %}
<br>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log-In" class="btn btn-primary" />
</form>
{% endblock content %}

video_player_app/templates/register.html
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SignUp" class="btn btn-primary" />
</form>

video_player_app/templates/upload_video.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

video_player_app/templates/video_detail.html
{% for video in videos %}
    <video width="320" height="240" controls>
        <source src="{{ video.video_file.url }}" type="video/mp4" >
        Your browser does not support the video tag.
    </video> 
    <br>
    <a href="{% url 'video:video_like' video.id %}" > Like </a>
    {{ video.likes_count }}
    <br>
    <a href="{% url 'video:comment' video.id %}" > Comment </a>
    <br>
    
    <a href="{% url 'video:subscribe' video.user.username  video.pk %}" > Subscribe </a>
    <br>
    Uploaded by : {{ video.user.username }}
    <br>
    <a href="{% url 'video:view_channel' video.user.username %}" > View Channel </a> 

    

{% endfor %}

video_player_app/templates/view_channel.html
<main>
    <div class="container">
      <h2 class="section-title">The videos of {{username}} are </h2>
      <div class="video-grid">
        {% for video in videos %}
          <div class="video">
            <a href="{% url 'video:video_detail' video.pk %}">
                <video width="320" height="240" controls>
                    <source src="{{ video.video_file.url }}" type="video/mp4" >
                    Your browser does not support the video tag.
                </video> 
            </a>
              <div class="video-info">
                <h3 class="#">{{ video.title }}</h3>
                <p class="#">{{ video.user }}</p>
                <p class="#">{{ video.upload_date|date }}</p>
                <p class="#">{{ video.description }}</p>
              </div>
            
          </div>
        {% endfor %}
      </div>
    </div>
  </main>


  The total subscribers are {{ subscribers }}